### PR TITLE
Fix/excessively wide time input box

### LINKED ISSUE #158: Time input box is excessively wide for Membrane Wrapping a Nanoparticle
## Description

The time input box next to the playback slider seems excessively wide for the trajectory "Membrane Wrapping a Nanoparticle."

image

## Expected Behavior

The box should have a width close to the width of the trajectory's final frame time + time step size.

## Reproduction

1. On staging, load Membrane Wrapping a Nanoparticle
2. See that the time input box is much wider than it needs to be

### PR DESCRIPTION
**Pull request by schoinh**
Problem
=======
Resolves #158 

Solution
========
Two fixes needed to be made to address the above bug with Membrane Wrapping a Nanoparticle:
1. Round the `refTimeValue` (`lastFrameTime + timeStep`) before determining its character length, because 5.44 + 0.08 = 5.520000000212455 of course
2. If the firstFrameTime is a very small (and long) number like 0.0008 (longer than `refTimeValue`), the input box needs to be long enough to accommodate that

## Type of change
Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)
* This change requires updated or new tests

Steps to Verify:
----------------
1. `npm start` and load Membrane Wrapping a Nanoparticle
2. The time input box should have sufficient (but not excessive) width to display the current time value at all times
3. Check the other networked trajectories

Screenshots (optional):
-----------------------
Before:
image

After:
image

Keyfiles (delete if not relevant):
-----------------------
* src/containers/ViewerPanel/selectors.ts - I moved the logic in `getTimeInputWidth` from PlaybackControls into here (as `getMaxNumChars`), and made it a function that the `getDisplayTimes` selector calls. `getMaxNumChars` now has the fixes described under "Solution".
* src/util/index.ts - I moved the `roundNumber` function from the `getDisplayTimes` selector into here and made it a util function that's called whenever we need to round a time value for display.

### CODE REVIEW

File: src/containers/ViewerPanel/selectors.ts [hunk 1]
```diff
@@ -52,32 +54,73 @@ export const convertUIDataToColorMap = (
     }, returnData);
 };
 
+// Determine the likely max number of characters for the time input box
+const getMaxNumChars = (
```
Comment (toloudis) [inline src/containers/ViewerPanel/selectors.ts:58]: i would unit test this function all by itself

**Review by toloudis — APPROVED** [review]
This looks great to me.  How about a simpler test that getMaxNumChars() returns the expected thing for a variety of numbers?

File: src/components/PlaybackControls/index.tsx [hunk 2]
```diff
@@ -100,16 +100,11 @@ const PlayBackControls = ({
...
     const getTimeInputWidth = (): string => {
-        // If lastFrameTime is 15 and step size is 0.25 then 15.25 is probably going to have
-        // the max number of characters for this trajectory
-        const refTimeValue =
-            displayTimes.roundedLastFrameTime + displayTimes.roundedTimeStep;
-        const maxNumChars = refTimeValue.toString().length;
         // If maxNumChars is 5 then the input box width will be 6 character widths long
         // (+ 1 is arbitrary padding)
-        return maxNumChars + 1 + "ch";
+        return displayTimes.maxNumChars + 1 + "ch";
```
Comment (toloudis) [inline src/components/PlaybackControls/index.tsx:107]: this might be less ambiguous as a formatted string `${(displayTimes.maxNumChars+1)}ch` or maybe just putting parens around the numbers...

**Review by toloudis — APPROVED** [review]

File: src/containers/ViewerPanel/test/selectors.test.ts [hunk 3]
```diff
@@ -70,7 +74,95 @@ describe("ViewerPanel selectors", () => {
...
+                },
+            };
+
+            const displayTimes = getDisplayTimes(mockState);
+
+            expect(displayTimes).to.deep.equal({
+                roundedTime: 3,
+                roundedLastFrameTime: 15,
+                roundedTimeStep: 0.08,
+                maxNumChars: 8,
```
Comment (meganrm) [inline src/containers/ViewerPanel/test/selectors.test.ts:106]: i'm not sure i understand why this is 8 since the rounded times are all to 2-3 sig figures.

**Review by EricJIsaac — APPROVED** [review]

File: src/containers/ViewerPanel/test/selectors.test.ts [hunk 4]
```diff
@@ -70,7 +74,95 @@ describe("ViewerPanel selectors", () => {
...
+            });
+        });
+    });
+
+    describe("getMaxNumChars", () => {
+        it("determines correct maxNumChars when time values are simple integers", () => {
```
Comment (meganrm) [inline src/containers/ViewerPanel/test/selectors.test.ts:112]: nit but I think it would be helpful to define what is "correct maxNum" here. Like, "if time values are simple integers, returns a max based on the largest value time can possibly be"

File: src/containers/ViewerPanel/test/selectors.test.ts [hunk 5]
```diff
@@ -70,7 +74,95 @@ describe("ViewerPanel selectors", () => {
...
+            const lastFrameTime = 44.1;
+            const timeStep = 0.8;
+
+            const maxNumChars = getMaxNumChars(
+                firstFrameTime,
+                lastFrameTime,
+                timeStep
+            );
+
+            expect(maxNumChars).to.equal(4); // "44.9".length()
```
Comment (meganrm) [inline src/containers/ViewerPanel/test/selectors.test.ts:137]: you could just put `expect(maxNumChars).to.equal("44.9".length())

File: src/util/index.ts [hunk 6]
```diff
@@ -76,3 +76,7 @@ export const wrapText = (
 export const clearUrlParams = () => {
     history.replaceState({}, "", `${location.origin}${location.pathname}`);
 };
+
+export const roundTimeForDisplay = (time: number): number => {
+    return parseFloat(time.toPrecision(3));
+};
```
Comment (meganrm) [inline src/util/index.ts:82]: i think we said in the test meeting that we want to cover utils too. It's a super simple function to test, but could be important incase we ever change the precision expectations

File: src/containers/ViewerPanel/test/selectors.test.ts (hunk 3 above)
Comment (schoinh) [reply src/containers/ViewerPanel/test/selectors.test.ts:106]: Ah, yeah it's because `firstFrameTime` is 0.000004. I guess I could do this instead like you suggested in another comment:
```
            expect(displayTimes).to.deep.equal({
                roundedTime: 3,
                roundedLastFrameTime: 15,
                roundedTimeStep: 0.08,
                maxNumChars: "0.000004".length(),
            })
```

File: src/containers/ViewerPanel/test/selectors.test.ts (hunk 5 above)
Comment (schoinh) [reply src/containers/ViewerPanel/test/selectors.test.ts:137]: Yesss

File: src/containers/ViewerPanel/test/selectors.test.ts (hunk 3 above)
Comment (meganrm) [reply src/containers/ViewerPanel/test/selectors.test.ts:106]: ah, i also can't quite count :)

File: src/containers/ViewerPanel/test/selectors.test.ts (hunk 4 above)
Comment (schoinh) [reply src/containers/ViewerPanel/test/selectors.test.ts]: Good call, I made them better

File: src/containers/ViewerPanel/test/selectors.test.ts (hunk 5 above)
Comment (schoinh) [reply src/containers/ViewerPanel/test/selectors.test.ts]: Done!

File: src/util/index.ts (hunk 6 above)
Comment (schoinh) [reply src/util/index.ts:82]: Done!

**Review by meganrm — APPROVED** [review]
