### PR TITLE
Fix/ make clearTrajectory just reset to initialState

### LINKED ISSUE #166: Reorganize redux state
## Use Case

For a Simularium developer, it would be nice to have redux state that is organized in a way that makes sense.

## Solution

Reorganize state to (per @meganrm):

1. simFileMetaData/modelMetaData or something
would hold all the data that comes from the back end when you select a model
2. status
would hold stuff like isBuffering, isPlaying, viewerStatus
3. selection
the same as it is, just move "draggedOverViewer" to status
4. simularium
right now would just have the controller, but in the future might have all the available trajectories

Also create a base state to revert to for all the state resetting tasks, like this https://medium.com/@justintulk/best-practices-for-resetting-an-es6-react-components-state-81c0c86df98d

See discussion: https://github.com/allen-cell-animated/simularium-website/pull/88#discussion_r541460619

### PR DESCRIPTION
**Pull request by schoinh**
Problem
=======
Closes #166 (This fix takes advantage of the Redux reorg that was recently completed)

Previously, because our Redux state tree was not organized properly, when we wanted to clear the trajectory info in our state (when loading a new trajectory) we had to specify which info (e.g. `firstFrameTime`, `timeStep`, etc.) to reset to initial state. And it seems this list of things to reset got forgotten/outdated. I'm not sure anyone ever came across a bug that arose from that, but it seems good to fix anyway.

Solution
========
Since the new `trajectory` state branch contains only the info that needs to be reset on a trajectory change, when we want to clear the trajectory info we can now just reset the entire branch to its `initialState` and not worry about forgetting a piece when we change what's in `initialState`.

You can see everything we now reset (i.e. what `initialState` looks like) here: https://github.com/allen-cell-animated/simularium-website/blob/main/src/state/trajectory/reducer.ts#L19

## Type of change
Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. `npm start` and try switching trajectories by different loading methods. Shouldn't run into any problems.

### CODE REVIEW

File: src/state/trajectory/logics.ts [hunk 1]
```diff
@@ -62,13 +62,7 @@ const resetSimulariumFileState = createLogic({
...
                 controller.clearFile();
             }
-            clearTrajectory = receiveTrajectory({
-                plotData: initialState.plotData,
-                firstFrameTime: initialState.firstFrameTime,
-                lastFrameTime: initialState.lastFrameTime,
-                timeStep: initialState.timeStep,
-                agentUiNames: initialState.agentUiNames,
-            });
+            clearTrajectory = receiveTrajectory(initialState);
```
Comment (toloudis) [inline src/state/trajectory/logics.ts:65]: safe to pass by ref?

**Review by toloudis — APPROVED** [review]

File: src/state/trajectory/logics.ts (hunk 1 above)
Comment (meganrm) [reply src/state/trajectory/logics.ts:65]: This does seem like it could cause problems since when we change state we're setting individual keys, instead
```suggestion
            clearTrajectory = receiveTrajectory({...initialState});
```

Comment (schoinh) [reply src/state/trajectory/logics.ts:65]: Yeah I wasn't sure about this, thanks for the input!

**Review by meganrm — APPROVED** [review]
